<?php
declare(strict_types=1);

/**
 * Generated by scripts/build_exam_home_highlights_index.php.
 * Do not edit manually; run the generator after catalog changes.
 */
function dent_exams_home_highlights_index(): array
{
    return array (
  'schemaVersion' => 1,
  'sourceSignature' => 'c9b36a556f47ef13a8f520b721a263d8d02a81a68da68bc19c75cf801839bb91',
  'defaultCatalogKey' => 'shared',
  'catalogByCohort' => 
  array (
    'dentistry-1402' => 'shared',
    'dentistry-1403' => 'shared',
    'dentistry-1404' => 'shared',
    'prosthesis-1402' => 'shared',
    'site-users' => 'shared',
  ),
  'catalogs' => 
  array (
    'shared' => 
    array (
      0 => 
      array (
        'catalogKey' => 'shared',
        'slug' => 'diagnostics-2-final-sample',
        'title' => 'نمونه سوالات پایان ترم تشخیصی ۲',
        'shortTitle' => 'نمونه سوالات تشخیصی ۲',
        'cardDescription' => 'فعلاً ۱ آزمون پایان‌ترم تشخیصی ۲ با مجموع ۴۸ سوال و پاسخ تشریحی در این مجموعه قرار گرفته است.',
        'heroDescription' => 'این مجموعه برای نمونه سوالات پایان‌ترم تشخیصی ۲ آماده شده و فعلاً شامل ۱ آزمون فعال با مجموع ۴۸ سوال است. در پاسخ هر سوال، گزینه علامت‌خورده در فایل، پاسخ تحلیلی، وضعیت مقایسه، رفرنس جزوه و بررسی تک‌تک گزینه‌ها نمایش داده می‌شود. با یک بار پرداخت ۳۰ هزار تومان، کل این مجموعه برای همین حساب فعال می‌شود و آزمون‌های بعدی همین مجموعه نیز از همین مسیر اضافه می‌شوند.',
        'addedAt' => '2026-07-19T14:24:47+03:30',
        'path' => '/exams/diagnostics-2-final-sample/',
        'stats' => 
        array (
          'examCount' => 1,
        ),
        'curriculum' => 
        array (
          'finalExam' => NULL,
        ),
      ),
      1 => 
      array (
        'catalogKey' => 'shared',
        'slug' => 'diagnostics-2-term6',
        'title' => 'آزمون های تمرینی پایان ترم تشخیصی ۲',
        'shortTitle' => 'تمرینی پایان ترم تشخیصی ۲',
        'cardDescription' => '۱۶ آزمون پایان‌ترم تشخیصی ۲ با مجموع ۶۶۰ سوال و پاسخ تشریحی در این بخش قرار گرفت.',
        'heroDescription' => 'این مجموعه برای درس تشخیصی ۲ ترم ۶ آماده شده و شامل ۱۶ آزمون فعال با مجموع ۶۶۰ سوال است. پاسخنامه هر سؤال به‌صورت جداگانه شامل پاسخ درست، دلیل درست‌بودن، بررسی گزینه‌ها و محل پاسخ در منبع نمایش داده می‌شود. با یک بار پرداخت ۳۰ هزار تومان، کل این مجموعه برای همین حساب فعال می‌شود.',
        'addedAt' => '2026-07-18T20:49:39+03:30',
        'path' => '/exams/diagnostics-2-term6/',
        'stats' => 
        array (
          'examCount' => 16,
        ),
        'curriculum' => 
        array (
          'finalExam' => 
          array (
            'expiresAt' => '2026-07-21T00:00:00+03:30',
          ),
        ),
      ),
    ),
  ),
);
}
