<?php
declare(strict_types=1);

/**
 * Generated by scripts/build_exam_home_highlights_index.php.
 * Do not edit manually; run the generator after catalog changes.
 */
function dent_exams_home_highlights_index(): array
{
    return array (
  'schemaVersion' => 1,
  'sourceSignature' => 'cff0e5108369a6dff3ddf2f805f362c8a0e65d9bf12803ae840d087061cd614d',
  'defaultCatalogKey' => 'shared',
  'catalogByCohort' => 
  array (
    'dentistry-1402' => 'shared',
    'dentistry-1403' => 'shared',
    'dentistry-1404' => 'shared',
    'prosthesis-1402' => 'shared',
    'site-users' => 'shared',
  ),
  'catalogs' => 
  array (
    'shared' => 
    array (
      0 => 
      array (
        'catalogKey' => 'shared',
        'slug' => 'complete-prosthodontics-midterm-sample',
        'title' => 'آزمون نمونه سوالات میانترم کامل نظری',
        'shortTitle' => 'نمونه سوالات میانترم',
        'cardDescription' => '۲ مجموعه نمونه‌سؤال میانترم کامل نظری با مجموع ۶۰ سؤال و پاسخ تشریحی.',
        'heroDescription' => 'این مجموعه برای پروتز کامل نظری ترم ۶ آماده شده و شامل ۲ آزمون با مجموع ۶۰ سؤال است. در پاسخ هر سؤال، گزینه علامت‌خورده در فایل، پاسخ پیشنهادی، وضعیت تطابق، وضعیت منبع، رفرنس/جزوه و بخش‌های آموزشی جداگانه نمایش داده می‌شود. با یک بار پرداخت ۳۰ هزار تومان، کل این مجموعه برای همین حساب فعال می‌شود.',
        'addedAt' => '2026-07-14T19:34:23+03:30',
        'path' => '/exams/complete-prosthodontics-midterm-sample/',
        'stats' => 
        array (
          'examCount' => 2,
        ),
        'curriculum' => 
        array (
          'finalExam' => 
          array (
            'expiresAt' => '2026-07-23T00:00:00+03:30',
          ),
        ),
      ),
      1 => 
      array (
        'catalogKey' => 'shared',
        'slug' => 'complete-foundations-theory-midterm-practice',
        'title' => 'آزمون های تمرینی میانترم مبانی کامل نظری',
        'shortTitle' => 'تمرینی میانترم',
        'cardDescription' => '۶ آزمون میانترم مبانی کامل نظری با مجموع ۲۹۰ سوال و پاسخ تشریحی در این بخش قرار گرفت.',
        'heroDescription' => 'این مجموعه برای درس پروتز کامل نظری ترم ۶ آماده شده و شامل ۶ آزمون فعال با مجموع ۲۹۰ سوال است. جلسه‌های ۵ و ۷ به‌دلیل هم‌پوشانی مبحث، در یک آزمون مشترک قرار گرفته‌اند. با یک بار پرداخت ۳۰ هزار تومان، کل این مجموعه برای همین حساب فعال می‌شود.',
        'addedAt' => '2026-07-13T14:45:00+03:30',
        'path' => '/exams/complete-foundations-theory-midterm-practice/',
        'stats' => 
        array (
          'examCount' => 6,
        ),
        'curriculum' => 
        array (
          'finalExam' => 
          array (
            'expiresAt' => '2026-07-23T00:00:00+03:30',
          ),
        ),
      ),
    ),
  ),
);
}
